name: Ejemplo de Composite action

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    env:
      MY_VAR: Mi variable de entorno

    steps:
      - name: Test
        run: echo "Valor ${{ vars.MY_VARIABLE_2 }}"

      - name: Secret
        run: echo "Secret ${{ secrets.MY_SECRET }}"